#관리자 권한 갖기
sudo: required

language: generic

services:
  - docker

#스크립트를 실행할 수 있는 환경, 도커 이미지 생성
before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t o37o19/docker-react-app -f Dockerfile.dev .

#실행할 스크립트
script: 
  - docker run -e CI=true o37o19/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success!!"